name: Package DKMS
run-name: >-
  Package-DKMS: ${{ github.head_ref || github.ref_name }}

# ========== TRIGGER ==========
on:
  workflow_dispatch:
  workflow_call:
    secrets:
      GHUB_TOKEN:
        required: true
      AZ_SAS_TOK:
        required: true

jobs:
  build_dkms_package:
    name: Build DKMS package

    runs-on:
      - self-hosted
      - builder

    strategy:
      fail-fast: false
      matrix:
        distro:
          - ubuntu:20.04
          - rockylinux:8.5

    container:
      image: ${{ matrix.distro }}
      volumes:
        - /mnt/cloud:/mnt/cloud
        - /mnt/local:/mnt/local
      options: "--entrypoint /bin/bash"

    steps:
      # --- INSTALL PRE-REQUISITES ---
      - name: APT | Update cache
        if: matrix.distro == 'ubuntu:20.04'
        run:  |
          apt-get update -y
          apt-get install -y software-properties-common
          add-apt-repository -y ppa:git-core/ppa
          apt-get update -y

      - name: APT | Install pre-requisite packages
        if: matrix.distro == 'ubuntu:20.04'
        run: >-
          apt-get -o Dpkg::Options::="--force-confdef"
          -o Dpkg::Options::="--force-confold" -y install
          git wget sudo gcc make automake dkms build-essential fakeroot devscripts debhelper findutils
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: DNF | Install epel
        if: matrix.distro == 'rockylinux:8.5'
        run: dnf install -y epel-release

      - name: DNF | Install pre-requisite packages
        if: matrix.distro == 'rockylinux:8.5'
        run: >-
          dnf install -y --enablerepo=powertools
          git wget sudo gcc make automake dkms rpm-build findutils

      - name: Clean up the working directory
        run: find -delete

      # --- CLONE REPOSITORIES ---
      - name: Checkout nfp driver kmods repo
        uses: Corigine/ci-libs/github_actions/utilities/checkout_corigine@main
        with:
          token: ${{ secrets.GHUB_TOKEN }}
          fetch-depth: 0

      - name: Install azcopy binary
        run: |
          wget https://aka.ms/downloadazcopy-v10-linux -O /tmp/downloadazcopy-v10-linux.tgz
          tar -xvf /tmp/downloadazcopy-v10-linux.tgz -C /tmp/
          sudo cp /tmp/azcopy_linux_amd64_*/azcopy /usr/bin/

      # --- COLLECT BUILD INFORMATION ---
      - name: Collect metadata
        id: describe
        run: |-2
          case "$DISTRO" in
            'ubuntu:20.04')
              BINARY_TYPE="deb"
              ;;
            'rockylinux:8.5')
              BINARY_TYPE="rpm"
              ;;
            *)
              BINARY_TYPE="unknown"
              ;;
          esac

          PACKAGE_NAME=$(.github/scripts/describe-head.sh --pkg_name)

          echo "pkg_name=${PACKAGE_NAME}" >> $GITHUB_OUTPUT
          echo "binary_type=${BINARY_TYPE}" >> $GITHUB_OUTPUT

          # DEFAULT_BRANCH defaults to public-main, but can be used to denote
          # other long-running branches for separate interim releases
          echo "default_branch=${DEFAULT_BRANCH}" >> $GITHUB_OUTPUT
        env:
          DISTRO: ${{ matrix.distro }}
          DEFAULT_BRANCH: public-main
          HEAD_REF: ${{ github.head_ref || github.ref_name }}

      # --- BUILD DKMS PACKAGE ---
      - name: Ubuntu | Build DEB DKMS package
        if: matrix.distro == 'ubuntu:20.04'
        run: sudo -E .github/scripts/package-dkms.sh -t d
        env:
          DEFAULT_BRANCH: ${{steps.describe.outputs.default_branch}}
          HEAD_REF: ${{ github.head_ref || github.ref_name }}

      - name: CentOS | Build RPM DKMS package
        if: matrix.distro == 'rockylinux:8.5'
        run: sudo -E .github/scripts/package-dkms.sh -t r
        env:
          DEFAULT_BRANCH: ${{steps.describe.outputs.default_branch}}
          HEAD_REF: ${{ github.head_ref || github.ref_name }}

      - name: Prepare environment for upload
        id: build_dest
        shell: bash
        run: |
          DATE="$(date -u +%Y.%m.%d)"

          temp_dir=$(pwd)
          cd ${BIN_TYPE}/${BIN_PKG_NAME}
          DKMS_PKG_NAME=$(ls ${BIN_PKG_NAME}-dkms*.${BIN_TYPE})
          cd $temp_dir

          echo "${BIN_TYPE}/${BIN_PKG_NAME}/${DKMS_PKG_NAME}"
          echo "${BIN_PKG_NAME}"

          # If the default branch is not 'public-main', append the branch name,
          # without 'wip-', to the upload destination
          if [ ! "$DEFAULT_BRANCH" = "public-main" ]; then
            DST_SUFFIX=".${DEFAULT_BRANCH#wip-}"
          fi
          case $HEAD_REF in
            "release-"*)
              TARGET_FOLDER=${HEAD_REF#*-}
              TARGET_FOLDER=${TARGET_FOLDER:0:5}
              AZURE_PATH="binaries/nfp-drv-dkms/releases${DST_SUFFIX}/${TARGET_FOLDER}"
              ;;
            "prerelease-"*)
              TARGET_FOLDER=${HEAD_REF#*-}
              TARGET_FOLDER=${TARGET_FOLDER:0:5}
              AZURE_PATH="binaries/nfp-drv-dkms/prereleases${DST_SUFFIX}/${TARGET_FOLDER}"
              ;;
            "${DEFAULT_BRANCH}")
              AZURE_PATH="binaries/nfp-drv-dkms/interim${DST_SUFFIX}/${BIN_PKG_NAME}"
              ;;
            *)
              AZURE_PATH="tmp/nfp_drv_dkms_builds${DST_SUFFIX}"
              AZURE_PATH="$AZURE_PATH/${{ github.actor }}/${DATE}"
              ;;
          esac

          AZURE_DEST=$(echo "${AZURE_PATH}/${BIN_TYPE}")
          echo "dkms_bin_path=$(echo "${BIN_TYPE}/${BIN_PKG_NAME}/${DKMS_PKG_NAME}")" >> $GITHUB_OUTPUT
          echo "azure_dest=${AZURE_DEST}" >> $GITHUB_OUTPUT
        env:
          DEFAULT_BRANCH: ${{steps.describe.outputs.default_branch}}
          BIN_TYPE: '${{ steps.describe.outputs.binary_type }}'
          BIN_PKG_NAME: '${{ steps.describe.outputs.pkg_name }}'
          HEAD_REF: ${{ github.head_ref || github.ref_name }}

      # --- UPLOAD DKMS PACKAGE TO AZURE ---
      - name: Upload to DKMS Package to Azure storage
        uses: Corigine/ci-libs/github_actions/azure/azcopy_upload_sync@main
        with:
          connection-string: ${{ secrets.AZ_SAS_TOK }}
          src: '${{ steps.build_dest.outputs.dkms_bin_path }}'
          dst: '${{steps.build_dest.outputs.azure_dest}}'

      - name: Clean up afterwards
        if: always()
        run: find -delete
